server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*log
    
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
            container_id: container_id
      
      - regex:
          expression: '^/var/lib/docker/containers/(?P<container_id>[^/]+)/.*$'
          source: filename
      
      - labels:
          container_id:
          stream:
      
      - timestamp:
          source: time
          format: RFC3339Nano

  - job_name: app
    static_configs:
      - targets:
          - localhost
        labels:
          job: crypto-server
          __path__: /var/log/crypto-server/*.log
    
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
            time: time
            caller: caller
      
      - labels:
          level:
      
      - timestamp:
          source: time
          format: RFC3339