#@TODO insert real corporative mail
global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@cryptoserver.com'
  smtp_auth_username: 'email@gmail.com'
  smtp_auth_password: 'password'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'team-notifications'
  
  routes:
    - match:
        severity: critical
      receiver: 'critical-notifications'
      continue: true
    
    - match:
        severity: warning
      receiver: 'warning-notifications'
      group_wait: 30s

receivers:
  - name: 'team-notifications'
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#alerts'
        title: 'Crypto Server Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}{{ end }}'

  - name: 'critical-notifications'
    email_configs:
      - to: 'admin@cryptoserver.com'
        headers:
          Subject: 'CRITICAL: {{ .GroupLabels.alertname }}'
    pagerduty_configs:
      - service_key: 'YOUR_PAGERDUTY_SERVICE_KEY'
        severity: 'critical'

  - name: 'warning-notifications'
    webhook_configs:
      - url: 'http://your-webhook-endpoint.com/alerts'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']